export const SESSION_LOGIN_SUCCESS = 'OX_SESSION_LOGIN_SUCCESS';
export const SESSION_LOGIN_FAILURE = 'OX_SESSION_LOGIN_FAILURE';
export const SESSION_LOGIN_REQUEST = 'OX_SESSION_LOGIN_REQUEST';
export const SESSION_LOGIN_RESET_FORM = 'OX_SESSION_LOGIN_RESET_FORM';
export const SESSION_LOGIN_RESET_ERROR = 'OX_SESSION_LOGIN_RESET_ERROR';
export const SESSION_LOGIN_FORM_SET_USERNAME = 'OX_SESSION_LOGIN_FORM_SET_USERNAME';
export const SESSION_LOGIN_FORM_SET_PASSWORD = 'OX_SESSION_LOGIN_FORM_SET_PASSWORD';
export const SESSION_LOGIN_FORM_SET_REMEMBERME = 'OX_SESSION_LOGIN_FORM_SET_REMEMBERME';
export const SESSION_LOGOUT = 'OX_SESSION_LOGOUT';
export const SESSION_USER_INFO = 'OX_SESSION_USER_INFO';

export const MAIL_LIST_REQUEST = 'OX_MAIL_LIST_REQUEST';
export const MAIL_LIST_SUCCESS = 'OX_MAIL_LIST_SUCCESS';
export const MAIL_LIST_ERROR = 'OX_MAIL_LIST_ERROR';

export const MAIL_FETCH_REQUEST = 'OX_MAIL_FETCH_REQUEST';
export const MAIL_FETCH_SUCCESS = 'OX_MAIL_FETCH_SUCCESS';
export const MAIL_FETCH_ERROR = 'OX_MAIL_FETCH_ERROR';

export const MAIL_SET_DISPLAY_FOLDER = 'OX_MAIL_SET_DISPLAY_FOLDER';

export const MAIL_FOLDERS_FETCH_REQUEST = 'OX_MAIL_FOLDERS_FETCH_REQUEST';
export const MAIL_FOLDERS_FETCH_SUCCESS = 'OX_MAIL_FOLDERS_FETCH_SUCCESS';

export const MAIL_HIDE = 'OX_MAIL_HIDE';
export const MAIL_HIDE_ALL = 'OX_MAIL_HIDE_ALL';
export const MAIL_MARK_READ = 'OX_MAIL_MARK_READ';

export const MAIL_COMPOSE_EDIT = 'OX_MAIL_COMPOSE_EDIT';
export const MAIL_COMPOSE_EDIT_UPDATE_SUBJECT = 'OX_MAIL_COMPOSE_EDIT_UPDATE_SUBJECT';
export const MAIL_COMPOSE_EDIT_UPDATE_BODY = 'OX_MAIL_COMPOSE_EDIT_UDPATE_BODY';
export const MAIL_COMPOSE_EDIT_UPDATE_TO = 'OX_MAIL_COMPOSE_EDIT_UPDATE_TO';
export const MAIL_COMPOSE_EDIT_UPDATE_CC = 'OX_MAIL_COMPOSE_EDIT_UPDATE_CC';
export const MAIL_COMPOSE_EDIT_UPDATE_BCC = 'OX_MAIL_COMPOSE_EDIT_UPDATE_BCC';
export const MAIL_COMPOSE_CLOSE = 'OX_MAIL_COMPOSE_CLOSE';

export const CONTACTS_SET_AUTOCOMPLETE = 'OX_CONTACTS_SET_AUTOCOMPLETE';

export const APP_SET_CURRENT = 'OX_APP_SET_CURRENT';