export const SESSION_LOGIN_SUCCESS = 'OX_SESSION_LOGIN_SUCCESS';
export const SESSION_LOGIN_FAILURE = 'OX_SESSION_LOGIN_FAILURE';
export const SESSION_LOGIN_REQUEST = 'OX_SESSION_LOGIN_REQUEST';
export const SESSION_LOGIN_RESET_FORM = 'OX_SESSION_LOGIN_RESET_FORM';
export const SESSION_LOGIN_RESET_ERROR = 'OX_SESSION_LOGIN_RESET_ERROR';
export const SESSION_LOGIN_FORM_SET_USERNAME = 'OX_SESSION_LOGIN_FORM_SET_USERNAME';
export const SESSION_LOGIN_FORM_SET_PASSWORD = 'OX_SESSION_LOGIN_FORM_SET_PASSWORD';
export const SESSION_LOGIN_FORM_SET_REMEMBERME = 'OX_SESSION_LOGIN_FORM_SET_REMEMBERME';
export const SESSION_LOGOUT = 'OX_SESSION_LOGOUT';

export const MAIL_LIST_REQUEST = 'OX_MAIL_LIST_REQUEST';
export const MAIL_LIST_SUCCESS = 'OX_MAIL_LIST_SUCCESS';

export const MAIL_FETCH_REQUEST = 'OX_MAIL_FETCH_REQUEST';
export const MAIL_FETCH_SUCCESS = 'OX_MAIL_FETCH_SUCCESS';

// export const MAIL_ALL_FOLDERS_FETCH_REQUEST = 'OX_MAIL_ALL_FOLDERS_FETCH_REQUEST';
// export const MAIL_ALL_FOLDERS_FETCH_SUCCESS = 'OX_MAIL_ALL_FOLDERS_FETCH_SUCCESS';

export const MAIL_FOLDERS_FETCH_REQUEST = 'OX_MAIL_FOLDERS_FETCH_REQUEST';
export const MAIL_FOLDERS_FETCH_SUCCESS = 'OX_MAIL_FOLDERS_FETCH_SUCCESS';

export const MAIL_HIDE_ALL = 'OX_MAIL_HIDE_ALL';

export const APP_SET_CURRENT = 'OX_APP_SET_CURRENT';